- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  salary: 40000
  setPreference: true # Lua
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9000 #2.5 hrs
  startingGear: DoctorGear
  alwaysUseSpawner: true
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-mmo # Frontier
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Paramedic
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # special: # Frontier
  # - !type:GiveItemOnHolidaySpecial # Frontier
  #   holiday: DoctorDay # Frontier
  #   prototype: WehMedipen # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Nanotrasen

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalDoctorChameleonOutfit
  job: MedicalDoctor
  equipment:
    head: ClothingHeadNurseHat
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
